## ndarray的基本索引

In [26]:
import numpy 
print('ndarray的基本索引')
x = numpy.array([[1,2],[3,4],[5,6]])
print(x[0]) # [1,2]
print(x[0][1]) # 2,普通python数组的索引
print(x[0,1]) # 同x[0][1]，ndarray数组的索引
x = numpy.array([[[1, 2], [3,4]], [[5, 6], [7,8]]])
print(x.shape)
print(x[0]) # [[1 2],[3 4]]
y = x[0].copy() # 生成一个副本
z = x[0] # 未生成一个副本
print(y) #  [[1 2],[3 4]]
print(y[0,0]) # 1
y[0,0] = 0 
z[0,0] = -1
print(y) # [[0 2],[3 4]]
print(x[0]) # [[-1 2],[3 4]]
print(z) # [[-1 2],[3 4]]


x = np.array([[1,2], [3,4], [5,6]])
print(x[:2])
print(x[:2][:1])
print(x[:2,:1])
x[:2,:1] = np.empty([2,1])# [[8],[9]]
print(x)
print(np.empty([2,1]))

ndarray的基本索引
[1 2]
2
2
(2, 2, 2)
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
1
[[0 2]
 [3 4]]
[[-1  2]
 [ 3  4]]
[[-1  2]
 [ 3  4]]


## ndarray 条件索引

In [41]:
print('ndarray 条件索引')
import numpy as np
npa = np.array(['a','b','c','d','e'])
print(npa.shape)
print(npa == 'a')
print(npa[npa>='c'])
print(npa[:2])
# a[(a=='c')]

(5,)
[ True False False False False]
['c' 'd' 'e']
['a' 'b']


## numpy 线性代数

In [90]:
print('numpy 线性代数')
# import numpy.linalg as nla
print('矩阵点乘')
x = numpy.array([[1,2],[3,4]])
y = numpy.array([[1,3],[2,4]])
print(x.dot(y)) # [[ 5 11][11 25]]
print(numpy.dot(x,y)) # # [[ 5 11][11 25]]
print('矩阵乘法')
print(x * y)
print(x + y)
print(x - y)
print(x / y)

numpy 线性代数
矩阵点乘
[[ 5 11]
 [11 25]]
[[ 5 11]
 [11 25]]
矩阵乘法
[[ 1  6]
 [ 6 16]]
[[2 5]
 [5 8]]
[[ 0 -1]
 [ 1  0]]
[[1.         0.66666667]
 [1.5        1.        ]]


 ## ndarray 排序

In [100]:
print('ndarray 排序')
x = numpy.array([[1,6,2],[6,1,3],[1,5,2]])
x.sort(axis=0)
print(x)
x.sort(axis=1)
print(x)

ndarray 排序
[[1 1 2]
 [1 5 2]
 [6 6 3]]
[[1 1 2]
 [1 2 5]
 [3 6 6]]


## ndarray的唯一化运算

In [93]:
print('ndarray的唯一化运算')
x = numpy.array([[1,6,2],[6,1,3],[1,5,2]])
print(numpy.unique(x))

ndarray的唯一化运算
[1 2 3 5 6]
